[package]
name = "wpa_cracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[dependencies]
hmac = "0.12.1"
itertools = "0.10.5"
ring = "0.16.20"
sha1 = "0.10.5"
